name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 2322
          POSTGRES_DB: profile_builder
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create database tables
      run: |
        PGPASSWORD=2322 psql -h localhost -U postgres -d profile_builder -f database/schema.sql
      
    - name: Run tests
      env:
        DB_USER: postgres
        DB_HOST: localhost
        DB_NAME: profile_builder
        DB_PASSWORD: 2322
        DB_PORT: 5432
        JWT_SECRET: test-secret-key
      run: npm test 