name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create required directories
      run: |
        mkdir -p public/uploads
        
    - name: Create env file
      run: |
        echo "PORT=3000" >> .env
        echo "DB_USER=postgres" >> .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_NAME=profile_builder" >> .env
        echo "DB_PASSWORD=2322" >> .env
        echo "DB_PORT=5432" >> .env
        echo "JWT_SECRET=your_secure_secret_here" >> .env
